-- ============================================================
-- ИМЯ. — база данных MVP
-- Запустить целиком в Supabase -> SQL Editor -> New query -> Run
-- ============================================================

create extension if not exists pgcrypto;

create table if not exists public.names (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  name_id uuid not null references public.names(id) on delete cascade,
  voter_hash text not null,
  ip_hash text not null,
  vote_date date not null,
  created_at timestamptz not null default now(),
  constraint votes_voter_day_unique unique (voter_hash, vote_date)
);

create index if not exists votes_name_id_idx on public.votes(name_id);
create index if not exists votes_vote_date_idx on public.votes(vote_date);
create index if not exists votes_ip_date_idx on public.votes(ip_hash, vote_date);

create table if not exists public.name_suggestions (
  id bigint generated by default as identity primary key,
  name text not null,
  normalized_name text not null unique,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

alter table public.names enable row level security;
alter table public.votes enable row level security;
alter table public.name_suggestions enable row level security;

-- Публичных политик намеренно нет: браузер не пишет напрямую в БД.
-- Все операции проходят через server-side API с SUPABASE_SECRET_KEY.

create or replace function public.cast_daily_vote(
  p_name_id uuid,
  p_voter_hash text,
  p_ip_hash text,
  p_vote_date date
)
returns table(name_id uuid, new_score bigint)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.names n
    where n.id = p_name_id and n.is_active = true
  ) then
    raise exception 'Name not found';
  end if;

  insert into public.votes(name_id, voter_hash, ip_hash, vote_date)
  values (p_name_id, p_voter_hash, p_ip_hash, p_vote_date);

  return query
  select p_name_id, count(*)::bigint
  from public.votes v
  where v.name_id = p_name_id;
end;
$$;

revoke all on function public.cast_daily_vote(uuid,text,text,date) from public;
grant execute on function public.cast_daily_vote(uuid,text,text,date) to service_role;

create or replace view public.name_ranking as
select
  n.id,
  n.name,
  n.slug,
  count(v.id)::bigint as score,
  count(v.id) filter (
    where v.vote_date = (now() at time zone 'Europe/Moscow')::date
  )::bigint as today_score
from public.names n
left join public.votes v on v.name_id = n.id
where n.is_active = true
group by n.id, n.name, n.slug;

-- ============================================================
-- Стартовый набор женских имён
-- ============================================================
insert into public.names(name, slug) values
('Александра','александра'),
('Алина','алина'),
('Алиса','алиса'),
('Алла','алла'),
('Алёна','алена'),
('Амина','амина'),
('Анастасия','анастасия'),
('Ангелина','ангелина'),
('Анна','анна'),
('Антонина','антонина'),
('Арина','арина'),
('Белла','белла'),
('Валерия','валерия'),
('Варвара','варвара'),
('Василиса','василиса'),
('Вера','вера'),
('Вероника','вероника'),
('Виктория','виктория'),
('Виолетта','виолетта'),
('Галина','галина'),
('Дарина','дарина'),
('Дарья','дарья'),
('Диана','диана'),
('Ева','ева'),
('Евгения','евгения'),
('Екатерина','екатерина'),
('Елена','елена'),
('Елизавета','елизавета'),
('Есения','есения'),
('Жанна','жанна'),
('Злата','злата'),
('Зоя','зоя'),
('Инна','инна'),
('Ирина','ирина'),
('Карина','карина'),
('Кира','кира'),
('Кристина','кристина'),
('Ксения','ксения'),
('Лариса','лариса'),
('Лейла','лейла'),
('Лиана','лиана'),
('Лидия','лидия'),
('Лилия','лилия'),
('Лина','лина'),
('Любовь','любовь'),
('Людмила','людмила'),
('Мадина','мадина'),
('Маргарита','маргарита'),
('Марина','марина'),
('Мария','мария'),
('Марьям','марьям'),
('Милана','милана'),
('Милена','милена'),
('Надежда','надежда'),
('Наталья','наталья'),
('Ника','ника'),
('Нина','нина'),
('Оксана','оксана'),
('Олеся','олеся'),
('Ольга','ольга'),
('Полина','полина'),
('Регина','регина'),
('Рената','рената'),
('Сабина','сабина'),
('Сафия','сафия'),
('Светлана','светлана'),
('Снежана','снежана'),
('София','софия'),
('Таисия','таисия'),
('Тамара','тамара'),
('Татьяна','татьяна'),
('Ульяна','ульяна'),
('Элина','элина'),
('Эльвира','эльвира'),
('Эмилия','эмилия'),
('Юлия','юлия'),
('Яна','яна'),
('Ясмина','ясмина')
on conflict (slug) do nothing;

-- ============================================================
-- Как одобрить предложенное имя вручную
-- 1) Посмотреть очередь:
-- select * from public.name_suggestions where status = 'pending' order by created_at;
--
-- 2) Добавить имя (пример):
-- insert into public.names(name, slug) values ('Адель', 'адель') on conflict do nothing;
-- update public.name_suggestions set status='approved', reviewed_at=now()
-- where normalized_name='адель';
-- ============================================================
